name: Release Server Image

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit sha"
        required: true
      tag:
        description: "The tag for the new image"
        required: true
      latest:
        type: boolean
        description: "Also update latest tag"
        required: true
        default: false
      major:
        type: boolean
        description: "Also update major tag"
        required: true
        default: false
      use-normal-source-tag:
        type: boolean
        description: "Use sha-<commit> source tag instead of legacy-sha-<commit>"
        required: true
        default: false

jobs:
  retag-and-release:
    name: "Re-tag and release server image"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "src/go.mod"
      - name: Copy server image
        env:
          COMMIT: ${{ github.event.inputs.commit }}
          TAG: ${{ github.event.inputs.tag }}
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PAT }}
          IMAGES: server
          SRC_REPO: temporaliotest
          DST_REPO: temporalio
          LATEST: ${{ github.event.inputs.latest }}
          MAJOR: ${{ github.event.inputs.major }}
          USE_NORMAL_SOURCE_TAG: ${{ github.event.inputs.use-normal-source-tag }}
        working-directory: ./src
        run: go run ./image_copy/main.go
